name: my_expense_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Firebase dependencies (updated versions)
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4

  # Database
  sqflite: ^2.4.2

  # Charting library
  fl_chart: ^0.70.2

  # Utility packages
  async: 2.12.0
  collection: ^1.19.1
  meta: ^1.16.0
  path: ^1.9.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
